### ISSUE TITLE
Different header types are not respected

### ISSUE THREAD

**Issue by daattali** [swarm-lab/editR#1]
Whether I use `#` or `##` or `###` or `####` all result in the same size in the preview panel (of course, when actually rendering the rmarkdown using pandoc, it looks correct)

**Comment by sjmgarnier** [comment]
Thanks. I'll look into it asap.

**Comment by sjmgarnier** [comment]
Ok, it should work now. It was just a problem with the css. I also added automatic numbering in preview. 

See changes at: https://github.com/swarm-lab/editR/commit/ce1041d54c2dbd42eb11963453f9e8499feaf4c7

**Comment by daattali** [comment]
Awesome :)  When I have a commit that fixes an issue, I like to link to the issue in the commit so that on this page it'll show exactly what's the code that fixed it.  Nice css skills

**Comment by sjmgarnier** [comment]
Google is entirely responsible for my css skills :-) 

By linking the issue in the commit, you mean just add the link in the commit message? Or something else? My git skills are still very limited :-)

**Comment by daattali** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/  
I think this is more of a GitHub rather than git thing, but it's pretty awesome. It automatically closes your issue and also adds a link in the issue to the commit

**Comment by sjmgarnier** [comment]
I guess it'll be for next time. I read that it's bad practice (maybe not possible) to modify the commit message after pushing it to remote. For now I'll just add the link manually in the comment closing this issue. Thanks for the tip though, it'll come in handy in the future.

**Comment by daattali** [comment]
Oh for sure, do not modify a commit, it can get ugly and weird. Was just a
tip for the future
