### ISSUE TITLE
Keep selected theme

### ISSUE THREAD

**Issue by LiNk-NY** [swarm-lab/editR#12]
The selected theme goes to the default after selecting one of the menu options in "File." 
Is there a way to set a permanent theme? 
Thanks.

Proposed labels: 
# bug
# enhancement

**Comment by sjmgarnier** [comment]
@LiNk-NY This was not an obvious one to solve. It should be fixed by 3a88ae98e6761b6813cdcc5ffcb9a1b1ee01891c. I also took advantage of this to overhaul the option system to make it consistent across sessions.
