### ISSUE TITLE
Set static Shiny port?

### ISSUE THREAD

**Issue by ghost** [swarm-lab/editR#16]
I'd like to set a static port for forwarding. Is it possible to surface this in the .editR options, or pass in as an argument?

**Comment by sjmgarnier** [comment]
@person157 No, it's not possible at the moment and I have no idea when it'll be possible to do it. 

So far `editR` has been a one man effort and this one man has a lot of other projects on his plate unfortunately. At the moment, I cannot make `editR` a priority and unless someone else helps me with developing the software further, it will remain in the current state. I will certainly try to keep the project alive, but it will be by random bursts, when I can get a long break from work.

**Comment by sjmgarnier** [comment]
@person157 I'll keep this issue open until I can find time to work on `editR` again.
