### ISSUE TITLE
make a RStudio addin?

### ISSUE THREAD

**Issue by dracodoc** [swarm-lab/editR#20]
If editR could have a RStudio addin to call editR on current opened file, it will be much easier to use than call the function manually.

Besides, does editR have to create all the object in the global environment?

**Comment by ghost** [comment]
An RStudio addin would be great, especially if it also included the ability to insert Markdown syntax into the R Markdown document being edited, e.g., bold, italics, link, image, footnote, etc.

**Comment by dracodoc** [comment]
Decided to do it by myself.  @richardlent you can have a try.
#24
