### ISSUE TITLE
Support for LaTeX

### ISSUE THREAD

**Issue by stared** [swarm-lab/editR#7]
Is there support for LaTeX (e.g. via MathJaX)?
As of now, I see all LaTeX formula not rendered.

**Comment by sjmgarnier** [comment]
@stared Can you provide an example? Also, does this happens when you try to render the document, or just in the preview panel?

**Comment by stared** [comment]
I mean - the preview. For rendering it works fine.

![screen shot 2015-05-23 at 17 25 45](https://cloud.githubusercontent.com/assets/1001610/7784797/cc0d8d2a-0172-11e5-893c-8adfa242ecb1.png)

**Comment by sjmgarnier** [comment]
@stared The problem is little more complicated than what I thought originally. I don't have much time to work on this at the moment but I'll come back to it as soon as I can.

**Comment by sjmgarnier** [comment]
@stared Actually it was pretty easy once I took the time to type "shiny mathjax" in Google to find this: http://shiny.rstudio.com/reference/shiny/latest/withMathJax.html. 

I push the modification to the repository (70752e43bfe6517a62f45253cb7901c8533c3c3c). Preview should now render your equations.

**Comment by stared** [comment]
Now it works like a charm! Thank you, @sjmgarnier.

**Comment by sjmgarnier** [comment]
No problem @stared. I'm just happy people find `editR` useful :-)
