### ISSUE TITLE
Preview stops working when using "Save file as"

### ISSUE THREAD

**Issue by sjmgarnier** [swarm-lab/editR#8]
When starting a new document in `editR` the preview stops working after the temporary document is saved.

**Comment by LiNk-NY** [comment]
The selected theme also goes to the default after selecting one of the menu options in "File." Is there a way to set a permanent theme? Thanks.

**Comment by sjmgarnier** [comment]
@LiNk-NY Can you open a separate issue for this problem? Thanks.

**Comment by sjmgarnier** [comment]
The problem seems to have disappeared since the latest round of changes to editR. Not sure what it was but I'm closing this issue now since it doesn't seem to be a problem anymore.
